<?php

include "archimedes.class.php";

/**
* Implementation of hook_menu().
*/
function archimedes_client_menu() {
  $items = array();
  $items['admin/reports/archimedes'] = array(
    'title' => t('Archimedes'),
    'access arguments' => array('access administration pages'),
    'page callback' => 'archimedes_out',
    'description' => t('Administer Archimedes'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['admin/reports/archimedes/data'] = array(
    'title' => t('Data'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/reports/archimedes/settings'] = array(
    'title' => t('Settings'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('archimedes_admin'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
   );
   $items['admin/reports/archimedes/export'] = array(
    'title' => t('XML Export'),
    'page callback' => 'archimedes_export',
    'access arguments' => array('access administration pages'),
    'type' => MENU_LOCAL_TASK,
   );
  return $items;
} // archimedes_client_menu()


function archimedes_out($arg=null) {
  $owl = archimedes_update();
  
  if ($arg == 'update') {
    $server_email = variable_get('archimedes_server_email',null);
    $site_name  = variable_get('site_name', "unknown");
    if ($server_email != null) {
      // need a way to bypass any mail hooks. as htmlmail has yet to add bypass functionality. maybe a solution is to use the php mail function instead.
      //drupal_mail('archimedes','send_xml',$server_email,language_default(),array('xml' => $owl->toXML()));
      $headers = 'From: ' . $site_name . ' <' . $owl->author . '>' . "\r\n";
      if (mail('Archimedes Server <' . $server_email . '>',t('XML Update from') . ' ' . $site_name,$owl->toXML(),$headers)) {
        drupal_set_message('Update sent successfully via email to '  . $server_email . '.');
      }
      else
        drupal_set_message('Update failed to send for an unknown reason.','error');
    } else {
      drupal_set_message('Update failed to send as the ' . l('server email address','reports/archimedes/settings') . ' is not yet set.','error');
    }
  }
  
  $header = array('Name','Version');

  $rows = array(
    array('Site title',$owl->getField('title')->getValues()),
    array('Description',$owl->getField('description')->getValues()),
    array('Servername',implode(', ',$owl->getField('field_servername')->getValues())),
    array('Web Server',implode(', ',$owl->getField('field_webserver')->getValues())),
    array('Web Root',$owl->getField('field_webroot')->getValues()),
    array('DB Host',$owl->getField('field_dbhost')->getValues()),
    array('DB Name',$owl->getField('field_dbname')->getValues()),
    array('Users',implode(', ',$owl->getField('field_users')->getValues())),
    array('DB Size',$owl->getField('field_db_size')->getValues()),
    array('Site Data Size',$owl->getField('field_sitedata')->getValues()),
    array('Webroot Size',$owl->getField('field_sitesize')->getValues()),
    array('User Count',$owl->getField('field_num_users')->getValues()),
    array('Modules',theme('table',$header,$owl->getField('field_drupal_mod')->getValues())),
    array('Themes',theme('table',$header,$owl->getField('field_drupal_theme')->getValues())),
  );
  
  
  $rows = array_merge($rows, module_invoke_all('archimedes_rows', $owl));
  
  $header = array('Component', 'Value');
  $output = '<p>This page shows the current output from of Archimedes Client for this website. It is not necessarily the same as what is known by the server.</p>';
  $output .= '<p>' . l('Force server update','admin/reports/archimedes/update') . '</p>';
  return $output . theme('table', $header, $rows);
  
  
} // archimedes_out()


function archimedes_export() {
  $owl = archimedes_update();

  return '<pre>' . htmlentities($owl->toXML()) . '</pre>';
  
} // archimedes_export()

function archimedes_update() {
  
  global $db_url;
  
  $author = db_result(db_query("SELECT mail FROM {users} WHERE uid = 1"));
  $owl = new Archimedes('drupal',$author);
  
  $field = $owl->createField('title', 'text');
  $field->addValue(variable_get('site_name', "unknown"));
  
  $field = $owl->createField('description', 'text');
  $field->addValue("[[Yet to do]]");
  
  $field = $owl->createField('field_servername', 'uri');
  $protocol = strpos(strtolower($_SERVER['SERVER_PROTOCOL']),'https') === FALSE ? 'http://' : 'https://';
  $field->addValue($protocol . $_SERVER["SERVER_NAME"]);
  
  $field = $owl->createField('field_webserver', 'node_reference');
  $field->invokeMulti();
  $hostname = archimedes_shell_exec("hostname -f");
  $field->addValue($hostname);
  
  $field = $owl->createField('field_webroot', 'text');
  $field->addValue($_SERVER["DOCUMENT_ROOT"]);
  
  $db = parse_url($db_url);
  $dbName = substr($db['path'],1);
  
  $field = $owl->createField('field_dbhost', 'node_reference');
  if ($db['host'] == 'localhost')
    $field->addValue($hostname);
  else
    $field->addValue($db['host']);
  
  $field = $owl->createField('field_dbname', 'text');
  $field->addValue($dbName);
  
  $field = $owl->createField('field_users', 'user_reference');
  $field->addValue('mailto:' . db_result(db_query("SELECT u.mail FROM {users} u WHERE uid = 1 LIMIT 1")));
  
  $field = $owl->createField('field_db_size', 'integer');
  $field->addValue(db_result(db_query("SELECT pg_database_size('".$dbName."')"))); //  currently only works for pgsql
  
  $field = $owl->createField('field_sitedata', 'integer');
  $dataSize = preg_split('/[\s]+/',archimedes_shell_exec("du -bsL ".$_SERVER['DOCUMENT_ROOT'].base_path().file_directory_path()));
  $field->addValue($dataSize[0]);
  
  $field = $owl->createField('field_sitesize', 'integer');
  $rootSize = preg_split('/[\s]+/',archimedes_shell_exec("du -bsL ".$_SERVER['DOCUMENT_ROOT'].base_path()));
  $field->addValue($rootSize[0]);
  
  $field = $owl->createField('field_num_users', 'integer');
  $field->addValue(db_result(db_query("SELECT COUNT(uid) FROM {users}"))-1); // subtract one for public user
  
  $mField = $owl->createField('field_drupal_mod', 'drupal_mod');
  $mField->invokeMulti();
  $tField = $owl->createField('field_drupal_theme', 'drupal_mod');
  $tField->invokeMulti();
  $result = db_query("SELECT d.name, d.info, d.type FROM {system} d");
  while ($d = db_fetch_object($result)) {
    $info = unserialize($d->info);
    if ($d->type == 'module')
      $mField->addValue(array('name' => $d->name, 'version' => $info['version']));
    elseif ($d->type == 'theme')
      $tField->addValue(array('name' => $d->name, 'version' => $info['version']));
  }
  
  drupal_alter('archimedes', $owl);
  
  return $owl;
  
  
} // archimedes_update()


function archimedes_admin() {
  $form = array();

  $form['archimedes_server_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Server email address'),
    '#default_value' => variable_get('archimedes_server_email', 'archimedes@server.com'),
    '#description' => t('Set Archimedes server email address.'),
  );
  
  $form['archimedes_server_location'] = array(
    '#type' => 'textfield',
    '#title' => t('Server web address'),
    '#default_value' => variable_get('archimedes_server_location', 'http://server.com'),
    '#description' => t('Set Archimedes server web address.'),
  );
  
  $form['archimedes_cron_update'] = array(
    '#type' => 'textfield',
    '#title' => t('Cron upate every x days'),
    '#default_value' => variable_get('archimedes_cron_update', 1),
    '#description' => t('Set Archimedes cron update period.'),
  );

  return system_settings_form($form);
}

// might not need this
function archimedes_mail($key, &$message, $params) {
  switch($key) {
    case 'send_xml':
      $message['subject'] = t('XML Update from ' . variable_get('site_name', "unknown"));
      $message['body'][] = $params['xml'];
      break;
  }
}



/**
* Utility functions.
*/
function archimedes_ends_with( $str, $sub ) {
   return ( substr( $str, strlen( $str ) - strlen( $sub ) ) === $sub );
} // archimedes_ends_with()

function archimedes_shell_exec($cmd) {
  $args = func_get_args();

  //do not change the command itself, just the parameters.
  for ($x = 1; $x < sizeof($args); $x++) {
    $args[$x] = escapeshellarg($args[$x]);
  }
  $command = call_user_func_array('sprintf', $args);

  exec($command . ' 2>&1', $output, $result);
  
  return $output[0];
} // archimedes_shell_exec()
